apiVersion: v1
kind: Service
metadata:
  name: broken-app-svc
  labels:
    app: broken-app
spec:
  selector:
    app: broken-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
